### ISSUE TITLE
python aebn_dl.py list.txt Not Working

### ISSUE THREAD

**Issue by MillerTimeJones** [estellaarrieta/aebn-vod-downloader#12]
I tried this python aebn_dl.py list.txt it doesn't work

PS C:\aebn-vod-downloader> python aebn_dl.py list.txt
Input URL: list.txt
Saving to: None
Traceback (most recent call last):
  File "C:\aebn-vod-downloader\aebn_dl.py", line 378, in <module>
    movie_instance.download()
  File "C:\aebn-vod-downloader\aebn_dl.py", line 55, in download
    self._scrape_info()
  File "C:\aebn-vod-downloader\aebn_dl.py", line 95, in _scrape_info
    content = html.fromstring(self.session.get(self.movie_url).content)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 575, in request
    prep = self.prepare_request(req)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 486, in prepare_request
    p.prepare(
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL 'list.txt': No scheme supplied. Perhaps you meant https://list.txt?
PS C:\aebn-vod-downloader>

I created a text file in the same dir as aebn-downloader and on sepeate lines I put the address for each film.

I have no issue with any of the other commands.

**Comment by estellaarrieta** [comment]
sorry, completely missed your issue(
Can you confirm the current dev version behaves the same way for you?
you can find it here - https://github.com/estellaarrieta/aebn-vod-downloader/blob/dev/aebn_dl.py

**Comment by scruffynerf** [comment]
still broken

**Comment by estellaarrieta** [comment]
just updated the dev branch again, tested list.txt on two systems, should work now

**Comment by scruffynerf** [comment]
on dev, list.txt is working but threads is not now:

```
$ aebndl list.txt -k -r 1080 -t 3
...
Total threads 5
```

**Comment by estellaarrieta** [comment]
fixed!
